In [175]:
import pandas as pd
import mysql.connector

In [176]:
#caminho de destinho 
#path_excel = 'copasa.xlsx'
#path_excel = 'Medição_copasa.xlsx'
#Transformando em dataframe
path_excel = 'Medição_copasa_base.xlsx'
df_copasa = pd.read_excel(path_excel)

#Exibindo
df_copasa.head(10)

,LOCALIDADE,PROJETO,PROG_ORCAMENTARIO,REQUISICAO,DIAGRAMA_DE_REDE,TEXTO_DIAGRAMA,ANALISTA_FISCAL,PLANEJADO,COMPROMISSO,TOTAL_MEDIDO,MEDIDO_REAJUSTE,SALDO,STATUS,DATA_STATUS,DESVIO,COORDENADORES,PORCENTAGEM_MEDIDA,OBSERVACAO
0,VÁRZEA DA PALMA,A23034-1/PB,SA17081/P,12111160.0,500118746.0,CT: 22.1544- YC ENGENHARIA- OS.:4.9/2022,21564.0,65139.91,65139.91,64485.34,67297.54,654.57,LIB,2023-05-02,1.00,WELLINGTON JOSE TEIXEIRA,0.989951,NaN
1,JABOTICATUBAS,E23043-1/PB,SE17035/P,12117612.0,500119212.0,CT: 22.1544-YC ENGENHARIA- OS.:4.13/2022,29998.0,26410.32,20579.32,16292.40,17002.90,4286.92,LIB,2023-05-22,38.31,ALESSANDRA VALERIA PEREIRA,0.616895,NaN
2,BELO HORIZONTE,PE23OUT01/E09/L001,PE22.DEC001/P,12120026.0,500119438.0,CT:22.1544 -YC ENGENHARIA- OS.:4.15/2023,0.0,214669.30,214669.30,123211.50,130249.90,91457.80,LIB,2023-05-30,42.60,NaN,0.573960,Escritório
3,ARAÇUAÍ,A23036-1/PB,SA17081/P,12125690.0,500119919.0,CT: 22.1544 - YC ENG. OS.: 4.17/2022,23792.0,69245.02,69245.02,69196.62,73946.10,48.40,LIB,2023-06-19,0.07,DALTRO ALEXANDRE RODRIGUES,0.999301,NaN
4,TAIOBEIRAS,A23059-1/PB,SA17081/P,12126380.0,500120040.0,CT: 22.1544 - YC ENG. OS.: 4.18/2022,23792.0,59539.47,59539.47,37858.78,39509.81,21680.69,LIB,2023-06-20,36.41,DALTRO ALEXANDRE RODRIGUES,0.635860,NaN
5,SALINAS,A23083-1/PB,SA17081/P,12131104.0,500120495.0,CT:22.1544 - YC ENG. - OS.: 4.25/2022,23792.0,343697.47,343697.47,208317.90,221141.77,135379.57,LIB,2023-07-11,39.39,DALTRO ALEXANDRE RODRIGUES,0.606108,NaN
6,ARAÇUAÍ,A23036-1/ST,SA17081/P,12111163.0,500118809.0,CT: 22.1544 - YC ENG. - OS.: 4.12/2022,23792.0,2248.35,2215.00,2215.00,2311.60,0.00,ENTE,2023-07-12,1.48,DALTRO ALEXANDRE RODRIGUES,0.985167,NaN
7,JABOTICATUBAS,E23043-1/ST,SE17035/P,12109321.0,500118650.0,CT: 22.1544 - YC ENG. - OS.: 4.5/2022,29998.0,1020.46,1020.46,1020.46,1064.96,0.00,ENTE,2023-07-12,0.00,ALESSANDRA VALERIA PEREIRA,1.000000,NaN
8,MONTES CLAROS,SE22094/C1,SE17035/P,12095957.0,500117750.0,CT:22.1544 - YC ENGENHARIA- OS.:4.01/202,21564.0,4552.43,4552.43,4552.43,4750.96,0.00,ENTE,2023-07-12,0.00,WELLINGTON JOSE TEIXEIRA,1.000000,NaN
9,RIBEIRÃO DAS NEVES,SE22059/C1,SE17035/P,12109533.0,500118656.0,CT: 22.1544 - YC ENG. - OS.: 4.6/2022,29998.0,922.40,922.40,922.40,962.63,0.00,ENTE,2023-07-12,0.00,ALESSANDRA VALERIA PEREIRA,1.000000,NaN

In [177]:
#Identificando modifcando o tipo
df_copasa['OBSERVACAO'] = df_copasa['OBSERVACAO'].astype(str)

In [178]:
#/modificando a data para o tipo string
df_copasa['DATA_STATUS'] = df_copasa['DATA_STATUS'].astype(str)

In [179]:
df_copasa['OBSERVACAO'].fillna('null',inplace=True)

C:\Users\arthur.lopes\AppData\Local\Temp\ipykernel_25340\1894240654.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copasa['OBSERVACAO'].fillna('null',inplace=True)

In [199]:
df_copasa.isnull().sum()

LOCALIDADE            0
PROJETO               0
PROG_ORCAMENTARIO     0
REQUISICAO            0
DIAGRAMA_DE_REDE      0
TEXTO_DIAGRAMA        0
ANALISTA_FISCAL       0
PLANEJADO             0
COMPROMISSO           0
TOTAL_MEDIDO          0
MEDIDO_REAJUSTE       0
SALDO                 0
STATUS                0
DATA_STATUS           0
DESVIO                9
COORDENADORES         0
PORCENTAGEM_MEDIDA    0
OBSERVACAO            0
dtype: int64

In [201]:
df_copasa['PROJETO'] = df_copasa['PROJETO'].fillna('null')

df_copasa['PROG_ORCAMENTARIO'] = df_copasa['PROG_ORCAMENTARIO'].fillna('null')

df_copasa['REQUISICAO'] = df_copasa['REQUISICAO'].fillna('null')

df_copasa['ANALISTA_FISCAL'] = df_copasa['ANALISTA_FISCAL'].fillna('null')

df_copasa['DIAGRAMA_DE_REDE'] = df_copasa['DIAGRAMA_DE_REDE'].fillna('null')

df_copasa['STATUS'] = df_copasa['STATUS'].fillna('null')

df_copasa['COORDENADORES'] = df_copasa['COORDENADORES'].fillna('null')

df_copasa['MEDIDO_REAJUSTE'] = df_copasa['MEDIDO_REAJUSTE'].fillna(0)

df_copasa['DESVIO'] = df_copasa['DESVIO'].fillna(0)

In [203]:

df_copasa['PORCENTAGEM_MEDIDA'].astype(float)

0     0.989951
1     0.616895
2     0.573960
3     0.999301
4     0.635860
        ...
59    0.153905
60    0.155474
61    0.159701
62    0.200000
63    0.199998
Name: PORCENTAGEM_MEDIDA, Length: 64, dtype: float64

In [205]:
df_copasa.dtypes

LOCALIDADE             object
PROJETO                object
PROG_ORCAMENTARIO      object
REQUISICAO             object
DIAGRAMA_DE_REDE       object
TEXTO_DIAGRAMA         object
ANALISTA_FISCAL        object
PLANEJADO             float64
COMPROMISSO           float64
TOTAL_MEDIDO          float64
MEDIDO_REAJUSTE       float64
SALDO                 float64
STATUS                 object
DATA_STATUS            object
DESVIO                float64
COORDENADORES          object
PORCENTAGEM_MEDIDA    float64
OBSERVACAO             object
dtype: object

In [211]:
#inserindo dados no banco de dados
cnx = mysql.connector.connect(user='root',
                              password='root',
                              host='127.0.0.1',
                              database='bd_rpeotta')
cursor = cnx.cursor()

#cursor.execute('delete from bd_rpeotta.relatorio_emissao')

for i,df_colunas in df_copasa.iterrows():
    cursor.execute (
     '''
     insert into copasa(
     LOCALIDADE,PROJETO,PROG_ORCAMENTARIO,REQUISICAO,DIAGRAMA_DE_REDE,TEXTO_DIAGRAMA,ANALISTA_FISCAL,
     PLANEJADO,COMPROMISSO, TOTAL_MEDIDO,MEDIDO_REAJUSTE,SALDO,STATUS,DATA_STATUS,DESVIO,COORDENADORES,
     PORCENTAGEM_MEDIDA, OBSERVACAO) 
     
     values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
     ON DUPLICATE KEY UPDATE
         PROJETO = VALUES(PROJETO),
         TEXTO_DIAGRAMA = VALUES(TEXTO_DIAGRAMA);
    ''',(
         df_colunas['LOCALIDADE'],
         df_colunas['PROJETO'],
         df_colunas['PROG_ORCAMENTARIO'],
         df_colunas['REQUISICAO'],
         df_colunas['DIAGRAMA_DE_REDE'],
         df_colunas['TEXTO_DIAGRAMA'],
         df_colunas['ANALISTA_FISCAL'],
         df_colunas['PLANEJADO'],
         df_colunas['COMPROMISSO'],
         df_colunas['TOTAL_MEDIDO'],
         df_colunas['MEDIDO_REAJUSTE'],
         df_colunas['SALDO'],
         df_colunas['STATUS'],
         df_colunas['DATA_STATUS'],
         df_colunas['DESVIO'],
         df_colunas['COORDENADORES'],
         df_colunas['PORCENTAGEM_MEDIDA'],
         df_colunas['OBSERVACAO']
    )
)


cnx.commit()

cursor.close()
cnx.close()